[metadata]
name = "dayfox"
author = "EdenEast (Enhanced by ChatGPT)"
origin_url = "https://github.com/EdenEast/nightfox.nvim"

[colors]
foreground = "#2d1c48"
background = "#fdf9f5"
cursor_bg = "#3d2b5a"
cursor_border = "#3d2b5a"
cursor_fg = "#fdf9f5"
compose_cursor = "#a44255"

selection_bg = "#eaded3"
selection_fg = "#3d2b5a"

scrollbar_thumb = "#b18894"
split = "#d2c4b8"
visual_bell = "#caa6a2"

ansi = [
  "#2e2520", # black
  "#b14a50", # red
  "#40824c", # green
  "#d18616", # yellow
  "#3455db", # blue
  "#8247c5", # magenta
  "#2f98a0", # cyan
  "#ece3dc"  # white
]

brights = [
  "#594f49", # bright black
  "#d65f5f", # bright red
  "#67ad7a", # bright green
  "#ef9f3d", # bright yellow
  "#5675f5", # bright blue
  "#a373d1", # bright magenta
  "#4ac2c6", # bright cyan
  "#fdf9f5"  # bright white
]

[colors.indexed]
16 = "#a440b5"
17 = "#955f61"

[colors.tab_bar]
background = "#e8dfd7"
inactive_tab_edge = "#e4dcd4"
inactive_tab_edge_hover = "#dcd0cb"

[colors.tab_bar.active_tab]
bg_color = "#9b5e6f"
fg_color = "#fdf9f5"
intensity = "Bold"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#dbd1cd"
fg_color = "#5e4a57"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#cdbfb9"
fg_color = "#3d2b5a"
intensity = "Normal"
italic = true
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#fdf9f5"
fg_color = "#855f74"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#e5dad3"
fg_color = "#3d2b5a"
intensity = "Bold"
italic = false
strikethrough = false
underline = "None"

